### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by tmattio**

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Thanks for the port (and it is an excellent branch for upstreaming), but could you make it a bit more minimal?

We try to patch as little as possible, because it is easier to merge the patched branch into future upstream releases for a new dune port when the code is as close to upstream as possible (minimizing merge conflicts etc). As such we usually leave unused variables (and run `dune build --profile release` as implied by `dune build -p`) and don't change VCS info nor the previous build system, just add `dune` files and modify the `opam` files.

**Review by NathanReb — COMMENTED** [review]
This is a great complete port. I'd suggest you open a PR upstream with exactly those changes.

For opam-overlays dune port though, we try to stick to the minimal set of changes so that users have an easy time picking up with what fundamental changes are involved for the dune port.

Tezos for instance expressed interest in having minimal dune ports.

With that in mind I'd suggest stripping out of this any change to travis CI scripts and documentation along with warning fixes since those won't show up in a duniverse.

**Comment by tmattio** [comment]
Thanks a lot for the speedy review!

No problem with making the port more minimal. To make sure I understand, should I also revert the changes to the build system files (the `build.ocp` and `META` files)?

> I'd suggest you open a PR upstream with exactly those changes.

I did 🙂 It's here: https://github.com/OCamlPro/ocp-ocamlres/pull/8

**Comment by NathanReb** [comment]
I think you can indeed leave the older build system files untouched as they don't have any impact on the dune port.

The META file could be confusing as it won't be used by dune but I guess it should be left untouched as well so the diff stays minimal.

**Comment by tmattio** [comment]
I've reverted the changes on non-dune/non-opam files. The build in release mode (`dune build --profile release`) is working.

**Review by NathanReb — COMMENTED** [review]
Sorry to for nitpicking but I think it would be even better if we do not generate the opam file as we can then preserve the opam field orders.

Then we're good to go!

**Comment by tmattio** [comment]
We don't - I've reverted some changes on the opam file in [5884c3e](https://github.com/dune-universe/ocp-ocamlres/pull/1/commits/5884c3e0beba8063b7363467908f9638e3ac1ad1) so the fields should have the same order now.

**Review by NathanReb — APPROVED** [review]
Looks great, thanks! You can go ahead with the release!

**Comment by tmattio** [comment]
> You can go ahead with the release!

Meaning I can merge this, push a tag and open a PR on opam-overlays, right?

**Pull request merged**
